name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Run Parasoft C/C++test
      # You may pin to the exact commit or the version.
      # uses: parasoft/run-cpptest-action@104f1c9cf6dbfd4b22e248a41d2e5a1e25e68b9e
      uses: parasoft/run-cpptest-action@1.0.0
      with:
        # Installation folder of Parasoft C/C++test. If not specified, the cpptestcli executable must be added to $PATH.
        installDir: /home/mlyko/sesja2021.1/github/cpptest
        # Working directory for running C/C++test.
        workingDir: /home/mlyko/sesja2021.1/github/actions-runner/_work/testcode/testcode
        # Identifier of a compiler configuration. Ensure you specify the configuration that matches your compiler.
        compilerConfig: gcc_7-64
        # Test configuration to be used for code analysis.
        # testConfig: builtin://Recommended Rules
        # Output folder for reports from code analysis.
        reportDir: reports
        # Format of reports from code analysis.
        reportFormat: xml,html,sarif
        # Input scope for analysis (typically, cpptestscan.bdf or compile_commands.json, depending on the project type and the build system).
        input: # optional, default is cpptestscan.bdf
        # Additional parameters for the cpptestcli executable.
        additionalParams: # optional, default is 
        # Command line pattern for running C/C++test.
        commandLinePattern: ${cpptestcli} -compiler "${compilerConfig}" -config "${testConfig}" -property report.format=${reportFormat} -report "${reportDir}" -module . -trace make clean all ${additionalParams}
    # Uploads analysis results in the SARIF format, so that they are displayed as GitHub code scanning alerts.
    - name: Upload results (SARIF)
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: reports/report.sarif
    
    # Uploads an archive that includes all report files (.xml, .html, .sarif).
    - name: Archive reports
      uses: actions/upload-artifact@v2
      with:
        name: Static analysis reports
        path: reports/*.*
